Replace chiaki by ng cause upstream build failure
Build logs:
```console
building '/nix/store/igg5ijs81wq5hx6ihz9fs0ffzkm9byj1-chiaki-2.2.0.drv'...
building '/nix/store/i87rrndj24kxb0q8ilagk37mgg78fbw1-mate-panel-1.28.6.drv'...
error: builder for '/nix/store/igg5ijs81wq5hx6ihz9fs0ffzkm9byj1-chiaki-2.2.0.drv' failed with exit code 1;
       last 19 log lines:
       > Running phase: qtPreHook
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/cgxb1i66qspa9280d1zwajzfskyficsg-chiaki
       > source root is chiaki
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LOCALEDIR=/nix/store/7xbkj673xy9ss1bakkqrshcggginqhja-chiaki-2.2.0/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/7xbkj673xy9ss1bakkqrshcggginqhja-chiaki-2.2.0/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/7xbkj673xy9ss1bakkqrshcggginqhja-chiaki-2.2.0/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/7xbkj673xy9ss1bakkqrshcggginqhja-chiaki-2.2.0/share/doc/chiaki -DCMAKE_INSTALL_INFODIR=/nix/store/7xbkj673xy9ss1bakkqrshcggginqhja-chiaki-2.2.0/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/7xbkj673xy9ss1bakkqrshcggginqhja-chiaki-2.2.0/share/man -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/7xbkj673xy9ss1bakkqrshcggginqhja-chiaki-2.2.0/include -DCMAKE_INSTALL_SBINDIR=/nix/store/7xbkj673xy9ss1bakkqrshcggginqhja-chiaki-2.2.0/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/7xbkj673xy9ss1bakkqrshcggginqhja-chiaki-2.2.0/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/7xbkj
       > CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
       >   Compatibility with CMake < 3.5 has been removed from CMake.
       >
       >   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
       >   to tell CMake that the project requires at least <min> but has been updated
       >   to work with policies introduced by <max> or earlier.
       >
       >   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
       >
       >
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/igg5ijs81wq5hx6ihz9fs0ffzkm9byj1-chiaki-2.2.0.drv'.
```